db_name: './listener_db.sqlite'
sample_dir: './samples'
test: true
samples_per_method: 2
likert:
    stm_struct:
        name: 'Short-term structure'
        st_name: 'ST-structure'
        desc: 'Whether the melody shows good structures in neighboring content, such as good repetitions and reasonable development.'
    ltm_struct:
        name: 'Long-term structure'
        st_name: 'LT-structure'
        desc: 'Whether the melody shows good structures in long distances, such as musical form and long-distance connections.'
    # repetitiveness:
    #     name: 'Overly repetitive (degenerate)'
    #     desc: 'Whether the melody repeats notes over and over.'
    complexity:
        name: 'Complexity'
        st_name: 'Complexity'
        desc: 'Whether the melody is complex in terms of rhythm and/or pitch.'
    overall_preference:
        name: 'Preference'
        st_name: 'Preference'
        desc: 'Overall preference to melody.' 
expertise: [
    "Beginner",
    "Intermediate",
    "Expert"
]
