<?php
    use App\Mut\Config;
    $config = Config::getConfig();
?>
<div class="modal" tabindex="-1" id='myModal'>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p><?php 
        $config = Config::getConfig();
        echo $config['description'];
        ?></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" id='myInput'>Close</button-->
        <!--button type="button" class="btn btn-primary" id='myInput'>Save changes</button-->
      </div>
    </div>
  </div>
</div>
<!--script>
const myModal = document.getElementById('myModal')
const myInput = document.getElementById('myInput')

myModal.addEventListener('shown.bs.modal', () => {
  myInput.focus()
})
myModal.modal();
</script-->
<p>
<?php 
    $config = Config::getConfig();
    echo $config['description'];
?>
</p>
<!--button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#myModal">
  Launch demo modal
</button-->
<form method="get" action="userstudy">
    <!--input id="nav" type="submit" value="Add"-->
    <!--button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#myModal"--->
    <button type="submit" class="btn btn-primary">
        Launch Listening Survey.
    </button>
</form>

