<?php
use App\Mut\DB;
$conn = DB::getConnection();
?>
  <!--div class="container"-->
    <div class='row'>
      <div class='col-lg-6'>
        <h2>Participant Information Sheet</h2>
        <p>
          <!--b>Full Title:</b> Listening Study – An Assessment on the Quality and Specificity of Computer-generated Singing with Artificially Converted Singing Techniques<br><br!>
          <b>Researcher's Name:</b> Brendan O'Connor (supervised by Prof Simon Dixon)</b><br>
          <b>Queen Mary Ethics of Research Committee reference number:</b> QMERC22.088</b><br>
          <b>Version number and date:</b> Version 0.1: 15.02.2022<br><br-->

          We want to invite you to be part of a research project. 
          Please read the following information carefully before you decide to take part. 
          This page will tell you why the research is being done and what you will be asked to do if you participate.<br><br>

          <b>Purpose of the study</b><br>

          This study aims to evaluate sampling techniques for neural network music generation. Specifically, we aim to analyze melodies' musical structure and complexity generated with different sampling strategies. dies.
          
            <br><br>
          <b>Experiment description</b><br>
          We are requesting you to listen to generated Irish folk melodies and rate them on the following attributes:
          from 1-5:
          <!--ul class='list-group'-->
              <!--?php
              foreach(DB::$config['likert'] as $key=>$likert){
                $measured = $likert['name'];
                $desc = $likert['desc'];
                // echo "<li class='list-group-item'>$measured</li>";
                echo "<button type='button' class='btn btn-light btn-sm' data-bs-container='body' data-bs-toggle='popover' data-bs-placement='right' data-bs-content='$desc'>$measured</button>";
                // break;
              }
              ?-->
          <!--/ul-->
          <dl class="row">
            <?php
              foreach(DB::$config['likert'] as $key=>$likert){
                $measured = $likert['name'];
                $desc = $likert['desc'];
                
                echo "<dt class='col-sm-4'>$measured</dt><dd class='col-sm-8'>$desc</dd>";
    
                #"<button type='button' class='btn btn-light btn-sm' data-bs-container='body' data-bs-toggle='popover' data-bs-placement='right' data-bs-content='$desc'>$measured</button>";
                
              }
              ?>
          </dl>
          The descriptions can be revisited during the experiment, by clicking the button on the right side. <b>Please ensure that your speakers or headphones are connected.</b>
          <!--Detailed instructions on how to proceed will be provided throughout the experiment, which takes approximately 10-15 minutes to complete. Please click <b>Next</b> to continue.<br><br>-->
        </p>
      </div>
    </div>
    <div class='row'>
      <div class='col-lg-6'>
        <form action="userstudy" method='get' >
          <label for="expertise_id" class="form-label">Please select your level of musical expertise below.</label>
          <select name="expertise_id" id="expertise_id" class="form-select"required>
            <option selected disabled value="">Select</option>
            <?php 
              $expertises = $conn->executeQuery("SELECT * FROM expertise")->fetchAllAssociative();
              foreach($expertises as $expertise){
                echo '<option value="'.$expertise["id"].'">'.$expertise["level"].'</option>"';
              }
            ?>
          </select>
          <div class="invalid-feedback">Please select expertise.</div>
          <button type="hidden" id="button" class="btn btn-primary">
            Next
          </button>
        </form>
      </div>
  </div>
<!-- Cookie Consent by FreePrivacyPolicy.com https://www.FreePrivacyPolicy.com -->
<script type="text/javascript" src="//www.freeprivacypolicy.com/public/cookie-consent/4.1.0/cookie-consent.js" charset="UTF-8"></script>
<script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({"notice_banner_type":"headline","consent_type":"express","palette":"light","language":"en","page_load_consent_levels":["strictly-necessary"],"notice_banner_reject_button_hide":false,"preferences_center_close_button_hide":false,"page_refresh_confirmation_buttons":false});
});
</script>

<noscript>Cookie Consent by <a href="https://www.freeprivacypolicy.com/">Free Privacy Policy Generator</a></noscript>
<!-- End Cookie Consent by FreePrivacyPolicy.com https://www.FreePrivacyPolicy.com -->





<!-- Below is the link that users can use to open Preferences Center to change their preferences. Do not modify the ID parameter. Place it where appropriate, style it as needed. -->

<a href="#" id="open_preferences_center">Update cookies preferences</a>
