<?php
$key =  array_keys($measured)[0];
$explenation = $measured[$key]['explenation'];
$name = $measured[$key]['name'];
echo "<div><a href='#' data-toggle='tooltip' tabindex='0' title='$explenation'>$name</a>";
// echo '<div><span class="d-inline-block" tabindex="0" data-toggle="tooltip" title="Disabled tooltip">
// <button class="btn btn-primary" style="pointer-events: none;" type="button" disabled>Disabled button</button>
// </span>';
for ($x = 1; $x < 6; $x++) {
    echo <<<EOS
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="$method-$key" id="inlineRadio$method-$key-$x" value="$x" required>
            <label class="form-check-label" for="inlineRadio$method-$key-$x">$x</label>
        </div>
    EOS;
  };
echo '</div>';
?>