<?php
    $key =  array_keys($measured)[0];
    $desc = $measured[$key]['desc'];
    $name = $measured[$key]['name'];
    // echo "<div class='col'><a href='#' data-toggle='tooltip' tabindex='0' title='$desc'>$name</a></div>";
    // echo '<div><span class="d-inline-block" tabindex="0" data-toggle="tooltip" title="Disabled tooltip">
    // <button class="btn btn-primary" style="pointer-events: none;" type="button" disabled>Disabled button</button>
    // </span>';


    echo '<div class="col">';
    for ($x = 1; $x < 6; $x++) {
        if($x == 5){
            $label = "&nbsp <a href='#' data-toggle='tooltip' tabindex='0' title='$desc'>$name</a>";
        }
        else{
            $label = "";
        }
        echo <<<EOS
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="$method-$key" id="inlineRadio$method-$key-$x" value="$x" required>
                <label class="form-check-label" for="inlineRadio$method-$key-$x">$x$label</label>
            </div>
        EOS;
    };
    echo '</div>';
?>