<form action="/submit" method="post">
    <?php
        use App\Mut\Config;
        $config = Config::getConfig();
        $shuffled = array_merge_recursive([], $data);
        shuffle($shuffled);
        // foreach($data as $method){
        foreach($shuffled as $method){
            echo "<div class='row'><audio controls src='./audio?method=$method'></audio><div>";
            foreach($config['likert'] as $key=>$measured){
                echo $this->fetch('./Likert.phtml', ['method'=> $method, "measured" => [$key=>$measured]]);
            }
        }
        
    ?>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>