<div class="row">
    <div class="col-lg-6">
        <form action="/submit" method="post">
            <?php
                use App\Mut\Config;
                use App\Mut\DB;
                $config = Config::getConfig();
                $samples = $data;
                // $shuffled = array_merge_recursive([], $data);
                $shuffled = array_merge_recursive([], array_keys($samples));
                shuffle($shuffled);
                if ($config['test']){
                    $method_dict = DB::getConnection()->executeQuery('SELECT * FROM sampling_method')->fetchAllAssociative();
                    $methods = [];
                    foreach($method_dict as $method){
                        $methods[$method['id']] = $method['name'];
                    }
                }
                foreach($shuffled as $local_sample_id){
                    echo "<div class='row'>";
                    $title = "";
                    if ($config['test']){
                        echo $methods[$samples[$local_sample_id]['method']];
                        if(isset($_COOKIE['exp'])) {
                           $res = DB::getConnection()->createQueryBuilder()->select('path')->from('samples')->where('id = ?')->setParameter(0, $samples[$local_sample_id]['id']);
                           $p_ = $res->fetchFirstColumn()[0];
                           $title = explode("/samples/",$p_)[1];
                          } 
                    }
                    echo"<audio controls title='$title' src='./audio?local_sample_id=$local_sample_id'></audio><div>";
                    foreach($config['likert'] as $key=>$measured){
                        echo $this->fetch('./Likert.phtml', ['local_sample_id'=> $local_sample_id, "measured" => [$key=>$measured]]);
                    }
                }
                
            ?>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>