<form action="/submit" method="post">
    <?php
        use App\Mut\Config;
        $config = Config::getConfig();
        foreach($data as $method){
            echo "<audio controls src='./audio?method=$method'></audio>";
            foreach($config['likert'] as $key=>$measured){
                echo $this->fetch('./Likert.phtml', ['method'=> $method, "measured" => [$key=>$measured]]);
            }
        }
        
    ?>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>